language: d
d:
  - dmd-2.073.2

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install libevent-dev expect-dev python3 python3-pip

install:
  - mkdir logs
  - pip3 install pyparsing
  - dub fetch doveralls

script:
  - dub test
  # TODO: Coverage
  # - rm .*.lst # hack for test coverage
  # - dub run doveralls
